config/routes.rb
Rails.application.routes.draw do
  resources :grades
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :classmates
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classmate.rb
class Classmate < ApplicationRecord
  validates :user_id, presence: true
  validates :first_name, :last_name, :email, :phone, presence: true

  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}

  validates :phone,
            :numericality => true,
            :length => { :minimum => 6, :maximum => 15 }
  # validates :email, :phone, uniqueness: true

  belongs_to :user
  validates_uniqueness_of :email, :phone, scope: :user_id

end

app/models/grade.rb
class Grade < ApplicationRecord
  validates :user_id, presence: true
  validates :code, :course, :points, :grade, presence: true

  validates_uniqueness_of :code, :course, scope: :user_id

  validates :points ,:numericality => true

  validates :grade, format: {with: /(?<=^|[\s,])(?:[A-D][-+]?|F)(?=[-+.]\B|[\s,]|$)/i , message: 'only allow american grades (A,B,C,D,F) '}

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable



  has_many :grades
  has_many :classmates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/classmates_controller.rb
class ClassmatesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_classmate, only: %i[ show edit update destroy ]

  before_action :correct_user, only: [:show,:edit, :update, :destroy]

  # GET /classmates or /classmates.json
  def index
    @classmates = Classmate.all

    @q = Classmate.ransack(params[:q])
    @classmates = @q.result(distinct: true)
  end

  # GET /classmates/1 or /classmates/1.json
  def show
  end

  # GET /classmates/new
  def new
    @classmate = Classmate.new
  end

  # GET /classmates/1/edit
  def edit
  end

  # POST /classmates or /classmates.json
  def create
    @classmate = Classmate.new(classmate_params)
    @classmate.user = current_user

    respond_to do |format|
      if @classmate.save
        format.html { redirect_to classmates_path}
        format.json { render :show, status: :created, location: @classmate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classmate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classmates/1 or /classmates/1.json
  def update
    respond_to do |format|
      if @classmate.update(classmate_params)
        format.html { redirect_to classmates_path }
        format.json { render :show, status: :ok, location: @classmate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classmate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classmates/1 or /classmates/1.json
  def destroy
    @classmate.destroy

    respond_to do |format|
      format.html { redirect_to classmates_url }
      format.json { head :no_content }
    end
  end

  private

  private
  def correct_user
    classmate = Classmate.find(params[:id])
    unless classmate.user == current_user
      redirect_to classmates_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classmate
      @classmate = Classmate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def classmate_params
      params.require(:classmate).permit(:first_name, :last_name, :email, :phone)
    end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :authenticate_user!

  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  before_action :set_grade, only: %i[ show edit update destroy ]


  # GET /grades or /grades.json
  def index
    @grades = Grade.all

    @q = Grade.ransack(params[:q])
    @grades = @q.result(distinct: true)
  end

  # GET /grades/1 or /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades or /grades.json
  def create
    @grade = Grade.new(grade_params)
    @grade.user = current_user

    respond_to do |format|
      if @grade.save
        format.html { redirect_to grades_path}
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1 or /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to grades_path}
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1 or /grades/1.json
  def destroy
    @grade.destroy

    respond_to do |format|
      format.html { redirect_to grades_url }
      format.json { head :no_content }
    end
  end

  def correct_user
    @grade = current_user.grades.find_by(id: params[:id])
    redirect_to grades_path, notice: "Not Authorized To Edit This grade!" if @grade.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grade_params
      params.require(:grade).permit(:code, :course, :points, :grade)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classmates_helper.rb
module ClassmatesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/classmates/_classmate.html.erb
<div id="<%= dom_id classmate %>">
  <p>
    <strong>First name:</strong>
    <%= classmate.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= classmate.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= classmate.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= classmate.phone %>
  </p>

</div>

app/views/classmates/_form.html.erb
<%= form_with(model: classmate) do |form| %>
  <% if classmate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(classmate.errors.count, "error") %> prohibited this classmate from being saved:</h2>

      <ul>
        <% classmate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">


      <div class="row mb-1 mt-4 h-100 justify-content-center align-items-center">
        <div class="col-sm-5">
          <%= form.text_field :first_name, placeholder: 'First name', class: 'form-control' %>
        </div>
      </div>

      <div class="row mb-1 mt-4 h-100 justify-content-center align-items-center">
        <div class="col-sm-5">
          <%= form.text_field :last_name, placeholder: 'Last name', class: 'form-control' %>
        </div>
      </div>


      <div class="row mb-1 mt-4 h-100 justify-content-center align-items-center">
        <div class="col-sm-5">
          <%= form.text_field :email, placeholder: 'Email', class: 'form-control' %>

        </div>
      </div>

      <div class="row mb-1 mt-4 h-100 justify-content-center align-items-center">
        <div class="col-sm-5">
          <%= form.text_field :phone, placeholder: 'Phone', class: 'form-control' %>
        </div>
      </div>

      <div class="text-center">
        <%= form.submit class: 'btn btn-primary mt-3 btn-sm'  %> <br>
        <%= link_to 'Cancel', classmates_path, class: 'btn btn-warning btn-sm mt-3' %>
      </div>
    </div>
  </div>
<% end %>

app/views/classmates/edit.html.erb
<h1 class="text-center">Edit classmate</h1>

<%= render "form", classmate: @classmate %>

<br>

app/views/classmates/index.html.erb
    <h1 class="text-start mx-3 reduce-gap">Your classmates</h1>

    <%= search_form_for @q do |f| %>


      <div class="form-group col-md-3 justify-content-center search-center">
        <%= f.search_field :first_name_cont, class: 'form-control  mt-3 ', placeholder: 'First name' %>
      </div>

      <div class="text-center">
        <%= f.submit class: 'btn btn-outline-primary btn-sm mt-3' %>
      </div>
    <% end %>


<div class="text-end mr-1">
  <%= link_to "New classmate", new_classmate_path, class: 'btn btn-primary btn-sm mx-5' %>
</div>
<hr>
<div class="container horizontal-scrollable">
  <table class="table table-striped">
    <thead>
    <tr>
      <th class="text-center">First name</th>
      <th class="text-center">Last name</th>
      <th class="text-center">Email</th>
      <th class="text-center">Phone</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @classmates.each do |classmate| %>
      <% if classmate.user == current_user %>
        <tr>
          <td class="text-center"><%= classmate.first_name %></td>
          <td class="text-center"><%= classmate.last_name %></td>
          <td class="text-center"><%= classmate.email %></td>
          <td class="text-center"><%= classmate.phone %></td>
          <td class="text-center"> <%= link_to 'View', classmate, class: 'btn btn-info btn-sm text-light' %> </td>
          <td class="text-center"> <%= link_to 'Edit', edit_classmate_path(classmate), class: 'btn btn-success btn-sm' %> </td>
          <td class="text-center"> <%= button_to 'Delete', classmate, method: :delete, class: 'btn btn-danger btn-sm ' %> </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/classmates/new.html.erb
<h1 class='text-center'>New classmate</h1>

<%= render "form", classmate: @classmate %>

<br>

app/views/classmates/show.html.erb
<div class="container horizontal-scrollable">
  <table class="table table-striped">
    <thead>
    <tr>
      <th class="text-center">Course code</th>
      <th class="text-center">Course</th>
      <th class="text-center">Points</th>
      <th class="text-center">Grade</th>
      <th class="text-center">Created at</th>
      <th class="text-center">Updated at</th>
      <th class="text-center"></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td class="text-center"><%= @classmate.first_name %></td>
      <td class="text-center"><%= @classmate.last_name %></td>
      <td class="text-center"><%= @classmate.email %></td>
      <td class="text-center"><%= @classmate.phone %></td>
      <td class="text-center"><%= @classmate.created_at %></td>
      <td class="text-center"><%= @classmate.updated_at %></td>
      <td class="text-center"> <%= link_to 'Go back', classmates_path, class: 'btn btn-warning btn-sm' %> </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/grades/_form.html.erb
<%= form_with(model: grade) do |form| %>
  <% if grade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
        <% grade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">


      <div class="row mb-1 mt-4 h-100 justify-content-center align-items-center">
        <div class="col-sm-5">
          <%= form.text_field :code,placeholder: 'Course code', class: 'form-control' %>
        </div>
      </div>



      <div class="row mb-1 mt-4 h-100 justify-content-center align-items-center">
        <div class="col-sm-5">
          <%= form.text_field :course,placeholder: 'Course name', class: 'form-control' %>

        </div>
      </div>


      <div class="row mb-1 mt-4 h-100 justify-content-center align-items-center">
        <div class="col-sm-5">
          <%= form.text_field :points,placeholder: 'Course points',class: 'form-control' %>


        </div>
      </div>

      <div class="row mb-1 mt-4 h-100 justify-content-center align-items-center">
        <div class="col-sm-5">
          <%= form.text_field :grade,placeholder: 'Course grade',class: 'form-control' %>
        </div>
      </div>

      <div class="text-center">
        <%= form.submit class: 'btn btn-primary mt-3 btn-sm'  %> <br>
        <%= link_to 'Cancel', grades_path, class: 'btn btn-warning btn-sm mt-3' %>
      </div>
    </div>
  </div>

<% end %>

app/views/grades/_grade.html.erb
<div id="<%= dom_id grade %>">
  <p>
    <strong>Code:</strong>
    <%= grade.code %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= grade.course %>
  </p>

  <p>
    <strong>Points:</strong>
    <%= grade.points %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= grade.grade %>
  </p>

</div>

app/views/grades/edit.html.erb
<h1 class="text-center">Edit grade</h1>

<%= render "form", grade: @grade %>

<br>

app/views/grades/index.html.erb
<h1 class="text-start mx-3 reduce-gap">Your grades</h1>


    <%= search_form_for @q do |f| %>


<div class="form-group col-md-3 justify-content-center search-center">
  <%= f.search_field :course_cont, class: 'search-center form-control  mt-3 ', placeholder: 'Course name' %>
</div>

        <div class="text-center">
          <%= f.submit class: 'btn btn-outline-primary btn-sm mt-3' %>
        </div>
    <% end %>

<div class="text-end mr-1">
  <%= link_to "New Grade", new_grade_path, class: 'btn btn-primary btn-sm mx-3' %>
</div>




<hr>
<div class="container horizontal-scrollable">
  <table class="table table-striped">
    <thead>
    <tr>
      <th class="text-center">Course code</th>
      <th class="text-center">Course</th>
      <th class="text-center">Points</th>
      <th class="text-center">Grade</th>
      <th class="text-center"></th>
    </tr>
    </thead>
    <tbody>
    <% @grades.each do |grade| %>
      <% if grade.user == current_user %>
        <tr>
          <td class="text-center"><%= grade.code %></td>
          <td class="text-center"><%= grade.course %></td>
          <td class="text-center"><%= grade.points %></td>
          <td class="text-center"><%= grade.grade %></td>
          <td class="text-center"> <%= link_to 'View', grade, class: 'btn btn-info btn-sm text-light' %> </td>
          <td class="text-center"> <%= link_to 'Edit', edit_grade_path(grade), class: 'btn btn-success btn-sm' %> </td>
          <td class="text-center"> <%= button_to 'Delete', grade, method: :delete, class: 'btn btn-danger btn-sm' %> </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/grades/new.html.erb
<h1 class="text-center">New grade</h1>

<%= render "form", grade: @grade %>

<br>

app/views/grades/show.html.erb
<div class="container horizontal-scrollable">
  <table class="table table-striped">
    <thead>
    <tr>
      <th class="text-center">Course code</th>
      <th class="text-center">Course</th>
      <th class="text-center">Points</th>
      <th class="text-center">Grade</th>
      <th class="text-center">Created at</th>
      <th class="text-center">Updated at</th>
      <th class="text-center"></th>
    </tr>
    </thead>
    <tbody>
        <tr>
          <td class="text-center"><%= @grade.code %></td>
          <td class="text-center"><%= @grade.course %></td>
          <td class="text-center"><%= @grade.points %></td>
          <td class="text-center"><%= @grade.grade %></td>
          <td class="text-center"><%= @grade.created_at %></td>
          <td class="text-center"><%= @grade.updated_at %></td>
          <td class="text-center"> <%= link_to 'Go back', grades_path, class: 'btn btn-warning btn-sm' %> </td>
        </tr>
    </tbody>
  </table>
</div>

app/views/home/_footer.erb
<!--
<footer class="text-center text-lg-start bg-light text-muted fixed-bottom mt-5">


  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="https://github.com/chubrubbaloo" target="_blank">chubrubbaloo</a>
  </div>
</footer>
 -->

app/views/home/_navbar.erb
<nav class="navbar navbar-expand-lg bg-secondary">
    <div class="container-fluid">
        <%= link_to 'EC-Demo', root_path, class:'navbar-brand text-light' %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <% if user_signed_in? %>

                <li class="nav-item">
                  <%= link_to 'Grades', grades_path, class: 'nav-link text-light text-center' %>
                </li>

                <li class="nav-item">
                  <%= link_to 'Classmates', classmates_path, class: 'nav-link text-light text-center' %>
                </li>
              <li class="nav-item">
                <%= link_to current_user.email, edit_user_registration_path, class: 'nav-link text-light text-center' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, class: 'nav-link text-light text-center' %>
              </li>

                <% else %>

              <li class="nav-item">
                <%= link_to 'Log in', new_user_session_path, class: 'nav-link text-light text-center' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link text-light text-center' %>
              </li>
                <% end %>
            </ul>

        </div>
    </div>
</nav>

app/views/home/index.html.erb
<div class="container-fluid px-4 py-5 my-5 text-center">
  <div class="lc-block d-block mx-auto mb-4">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" width="5em" height="5em" lc-helper="svg-icon" fill="currentColor">
      <path d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm121.8 169.9l-40.7 191.8c-3 13.6-11.1 16.9-22.4 10.5l-62-45.7-29.9 28.8c-3.3 3.3-6.1 6.1-12.5 6.1l4.4-63.1 114.9-103.8c5-4.4-1.1-6.9-7.7-2.5l-142 89.4-61.2-19.1c-13.3-4.2-13.6-13.3 2.8-19.7l239.1-92.2c11.1-4 20.8 2.7 17.2 19.5z"></path>
    </svg>
  </div>
  <div class="lc-block">
    <div editable="rich">

      <h2 class="display-5 fw-bold">This application is for demonstration purposes only</h2>

    </div>
  </div>
  <div class="lc-block col-lg-6 mx-auto mb-4">
    <div editable="rich">
      <br>

      <p class="lead">This project was built with Ruby on Rails following the MVC pattern, HTML(erb) for generating the view, Bootstrap for developing a responsive layout and finally SQLite for storing, maintaining and accessing the data.</p>

    </div>
  </div>

  <div class="lc-block d-grid mb-5 gap-2 d-sm-flex justify-content-sm-center"> <a class="btn btn-primary btn-lg px-4 gap-3" href="https://ecutbildning.se/" target="_blank" role="button">EC-Utbildning</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>

  <%= render 'home/navbar' %>

  <p class="text-center"><%= notice %></p>
  <p class="text-center alert"><%= alert %></p>


  <%= yield %>

  <%= render 'home/footer' %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>